# Generated by Django 3.2.6 on 2021-08-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='none', max_length=70),
            preserve_default=False,
        ),
    ]
