# Generated by Django 3.2.6 on 2021-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='aid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
