# Generated by Django 3.2.6 on 2021-08-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_blog_aid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(max_length=12000),
        ),
    ]
